#!/bin/bash
#####################################################################################
#####################################################################################
########################## SERTİFİKA YÜKLEME ########################################
#####################################################################################
#####################################################################################
#####################################################################################
#### Kurumumuzun sertifikasını PC ye yüklemek için ilgili yere kopyalıyoruz. ########
#cp /opt/afad-app-fix/AFADK.crt /usr/local/share/ca-certificates/
#### non-interactively olarak kopyaladığımız sertifikayı yükler #####################
#update-ca-certificates
#echo " Afad 2020 Kurumsal Sertifika Yüklendi"
#####################################################################################
#####################################################################################
########################## Google-EARTH FIX #########################################
#####################################################################################
#####################################################################################
#####################################################################################
################## Locate hatası giderilmesi ########################################
earth_file2=$(less /opt/google/earth/pro/googleearth | head -1 |grep -F LC_NUMERIC | wc -l)
if [ "$earth_file2" -lt "1" ] ; then
echo ok
else 
sed -i 1,1d /opt/google/earth/pro/googleearth
fi
earth_file1=$(less /opt/google/earth/pro/googleearth |grep -F LC_NUMERIC | wc -l)
if [ "$earth_file1" -lt "1" ] ; then
sed  -i '7i export LC_NUMERIC=C' /opt/google/earth/pro/googleearth
else 
echo ok
fi
#####################################################################################
###############################Samba ayari###########################################
smb_file1=$(less /etc/samba/smb.conf |grep paylas* | wc -l)
if [ "$smb_file1" -lt "1" ] ; then
echo """    
	[paylas]
    comment = Dosya paylasimi
    path = /home/paylas/
    browseable = yes
    guest ok = yes
    read only = no
    public = yes
    writable = yes

""" >> /etc/samba/smb.conf
else 
echo ok
fi

#####################################################################################
###############################NTP ayari###########################################
cp /opt/afad-app-fix/ntp.conf /etc/

#####################################################################################
###############################sudo ayari###########################################
district=(Merkez  Adana  Adiyaman  Afyon  Agri  Amasya  Ankara  Antalya  Artvin  Aydin  Balikesir  Bilecik  Bingol  Bitlis  Bolu  Burdur  Bursa  Canakkale  Cankiri  Corum  Denizli  Diyarbakir  Edirne  Elazig  Erzincan  Erzurum  Eskisehir  Gaziantep  Giresun  Gumushane  Hakkari  Hatay  Isparta  Icel  Istanbul  Izmir  Kars  Kastamonu  Kayseri  Kirklareli  Kirsehir  Kocaeli  Konya  Kutahya  Malatya  Manisa  Kahramanmaras  Mardin  Mugla  Mus  Nevsehir  Nigde  Ordu  Rize  Sakarya  Samsun  Siirt  Sinop  Sivas  Tekirdag  Tokat  Trabzon  Tunceli  Sanliurfa  Usak  Van  Yozgat  Zonguldak  Aksaray  Bayburt  Karaman  Kirikkale  Batman  Sirnak  Bartin  Ardahan  Igdir  Yalova  Karabuk  Kilis  Osmaniye  Duzce )
MYIP=$(ip route get 10.100.10.110 | head -1 | cut -d' ' -f7)
#MYIP="10.45.1.15"
PLAKA=$(echo $MYIP | cut -d'.' -f2)
#echo $PLAKA
if [ "$PLAKA" -lt "82" ] ; then
#echo ${district[$PLAKA]}
echo "%gYT-"${district[$PLAKA]}"HelpDesk ALL=(ALL) ALL " > /etc/sudoers.d/domaingroups
chmod 644 /etc/sudoers.d/domaingroups
else
echo Plaka Yok
fi
#####################################################################################
chmod 777 /opt/afad/afad*
chmod 777 /etc/xdg/autostart/afad-remote.desktop

#####################################################################################
#####################################################################################
##########################   Uygulama isimleri ######################################
#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
##################  Peynir isim düzeltme  ###########################################
sed -i 's+Name\[tr\]=Peynir+Name\[tr\]=Webcam - Peynir+g' /usr/share/applications/org.gnome.Cheese.desktop

##################Stacer Sistem Temizleme############################
stacer_file1=$(less /usr/share/applications/stacer.desktop |grep -F Name[tr] | wc -l)
if [ "$stacer_file1" -lt "1" ] ; then
echo """Name[tr]=Sistem Temizleme
""" >> /usr/share/applications/stacer.desktop
else 
echo ok
fi
find /home -type d -name ".config" -exec cp -r /etc/skel/.config/stacer "{}"/ \;

################## Müzik Çalar ############################
audacious_file1=$(less /usr/share/applications/audacious.desktop |grep -F Name[tr] | wc -l)
if [ "$audacious_file1" -lt "2" ] ; then
echo """Name[tr]=Müzik Çalar
""" >> /usr/share/applications/audacious.desktop
else 
echo ok
fi
find /home -type d -name ".config" -exec cp -r /etc/skel/.config/audacious "{}"/ \;

################### Uzak Masaüstü İstemcisi ###########
sed -i 's+Name\[tr\]=KRDC+Name\[tr\]=Uzak Masaüstü İstemcisi+g' /usr/share/applications/org.kde.krdc.desktop
sed -i 's+Icon=.*+Icon=preferences-desktop-remote-desktop+g' /usr/share/applications/org.kde.krdc.desktop

################### Sistem Bilgileri ###########
hardinfo_file1=$(less /usr/share/applications/hardinfo.desktop |grep -F Name[tr] | wc -l)
if [ "$hardinfo_file1" -lt "1" ] ; then
echo """Name[tr]=Sistem Bilgileri
""" >> /usr/share/applications/hardinfo.desktop
else 
echo ok
fi

########## Belge Tarayıcısı #########
cp -r /opt/afad-app-fix/simple-scan.desktop /usr/share/applications/simple-scan.desktop

################### uGet ###########
uget_gtk_file1=$(less /usr/share/applications/uget-gtk.desktop |grep -F Name[tr] | wc -l)
if [ "$uget_gtk_file1" -lt "1" ] ; then
echo """Name[tr]=uGet - İndirme Yöneticisi
""" >> /usr/share/applications/uget-gtk.desktop
else 
echo ok
fi
################### galculator ###########
galculator_file1=$(less /usr/share/applications/galculator.desktop |grep -F Name[tr] | wc -l)
if [ "$galculator_file1" -lt "1" ] ; then
echo """Name[tr]=Hesap Makinesi
""" >> /usr/share/applications/galculator.desktop
else 
echo ok
fi

############### kdenlive #########
sed -i 's+Name\[tr\]=Kdenlive+Name\[tr\]=Video Düzenleyici+g' /usr/share/applications/org.kde.kdenlive.desktop

########## Kazam ##########################
sed -i 's+Name\[tr\]=Kazam+Name\[tr\]=Ekran Video Kaydı+g' /usr/share/applications/kazam.desktop

########### mugshot---hakkında yardım link değişimi ################################################
sed -i 's+show_uri(self, "https://wiki.bluesabre.org/doku.php?id=mugshot-docs")+show_uri(self, "https://pardus.org.tr/sss")+g' /usr/lib/python3/dist-packages/mugshot_lib/Window.py

########## org.gnome.Usage #########
cp /opt/afad-app-fix/org.gnome.Usage.desktop /usr/share/applications/

########## gnome-system-monitor #########
cp /opt/afad-app-fix/gnome-system-monitor.desktop /usr/share/applications/

########## Xfburn ##########################
sed -i 's+Name\[tr\]=Xfburn+Name\[tr\]=CD-DVD YAZICI+g' /usr/share/applications/xfburn.desktop

########## auto hplip ##########################
rm /etc/xdg/autostart/hplip-systray.desktop

#############Calibre font düzeltme#################
rm /usr/share/fonts/wps-fonts/calibri*

#####Kötü dizinleri siler######
find /home /root /etc/skel -type d -name "模板" -exec rm -r "{}" \;

cp /opt/afad-app-fix/de.qm /opt/zoom/translations/

